### ISSUE TITLE
Hello, when can the code be updated?

### ISSUE THREAD

**Issue by viego1999** [ShilinSun/LGCL#1]

**Comment by lei-liu1** [comment]
Hello, @ShilinSun 

I am looking forward to the source codes, too. When will they be released?
Thanks in advance.

Best regards

**Comment by liyingjack** [comment]
Looking forward the source code too!

**Comment by jm-zh** [comment]
I am looking forward to the source codes, too.

**Comment by ShilinSun** [comment]
Thanks for your attention. Unfortunately, because some files have not been sorted out, they cannot been uploaded at the moment. If you are interested in line graph and contrastive learning, please refer to the baseline code in references. They are all good work.  We deeply regret the trouble this has caused.
